balena-io/sshproxy

- .editorconfig
- .gitignore
- LICENSE
- Makefile
- README.md
- resin/README.md
- resin/main.go
- sshproxy.go
Connects to #1 
Change-Type: major
Depends: resin-io/pinejs-client-go#7
> initial release

- sshproxy.go
Connects-to: #37
Change-type: minor
> fix incorrect parsing of payload lengths

- .circleci/config.yml
- Makefile
- README.md
- balena/README.md
- balena/auth.go
- balena/main.go
- sshproxy.go
> golang: update to Go v1.11.2

- balena/auth.go
> Remove unnecessary brackets from filter

- .circleci/config.yml
- balena/auth.go
> Update to Go v1.11.4 & use Balena api v5 endpoints

- .circleci/config.yml
- balena/auth.go
- balena/main.go
- sshproxy.go
> update to Go v1.11.5

- .circleci/config.yml
- .github/CODEOWNERS
- Makefile
> update to Go v1.12 and add CODEOWNERS

- .circleci/config.yml
> update to Go v1.12.1

- .circleci/config.yml
> update to Go v1.12.4

- sshproxy.go
> do not pass EOF errors to handler

- .circleci/config.yml
- sshproxy.go
> ignore common tcp errors at low verbosity levels

- sshproxy.go
> default to PEM format when calling ssh-keygen

- balena/main.go
- sshproxy.go
> allow specifying a whitelist of env vars to pass from client

- .circleci/config.yml
> Update to Go v1.12.9

- .circleci/config.yml
> update to Go v1.13.4

- main.go
---
fork was used in testing and ultimately proved to be unnecessary.
> revert to pires proxyproto library

- .circleci/config.yml
- .errcheck.exclude
- ssh.go
> explicitly close Pty when Session ends

- .circleci/config.yml
- .github/CODEOWNERS
> update to Go v1.14.6

- .circleci/config.yml
- .github/CODEOWNERS
> Update to golang v1.17.3

- .circleci/config.yml
- Makefile
> Update to golang v1.18.0

- Makefile
> Fix release uploading

- .github/workflows/flowzone.yml
> Build on Ubuntu 20 to force GCLIB compatibility

- docker-compose.test.yml
> Build static binary
